start_time = Sys.time()
time1 = Sys.time()

source("./script/initial_parameters.R")
time2 = Sys.time()

print(time2 - time1)

source("./script/multinomial_gen.R")
time1 = Sys.time()
print(time1 - time2)
source("./script/risk_gen.R")
time2 = Sys.time()
print(time2 - time1)
source("./script/risks_and_probs_gen.R")
time1 = Sys.time()
print(time1 - time2)
# source("./script/simulation_gen.R")
# time2 = Sys.time()
# print(time2 - time1)
# source("./script/expand_simulations.R")
# time2 = Sys.time()
# print(time2 - time1)
source("./script/model_failure_&coverage.R")
time2 = Sys.time()
print(time2 - time1)

end_time = Sys.time()

print(end_time - start_time)
